React capstone project - Metrics webapp 🧢
ismailmunyentwari9/react-capstone pull request #1
Opened 2023-04-19 12:21 UTC by ismailmunyentwari9

# What I have done in this project 🥇 

- [ ] Select the API .
- [ ] Build files structure for  React app.
- [ ] Prepare routes and navigation in  app.
- [ ] Create the tests for the application.
- [ ] Style  components to match the design provided.
- [ ] Deploy the project and test for final details.
- [ ] Record a video for  project.
- [ ] Create a good README and PR description.

# 🧠Skills Gained ♻️ 

- [ ] Use React documentation.
- [ ] Use React components.
- [ ] Use React props.
- [ ] Use React Router.
- [ ] Connect React and Redux.
- [ ] Handle events in a React app.
- [ ] Write integration tests with a React testing library.
- [ ] Use styles in a React app.
- [ ] Use React life cycle methods.
- [ ] Apply React best practices and language style guides in code.
- [ ] Use store, actions and reducers in React.

2023-04-19 13:44 UTC, julie-ify reviewed
Hi @ismailmunyentwari9,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that does not have a descriptive readme file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-19 16:07 UTC, rloterh requested changes
Hi Isma, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project, but you are almost there!  
🏁  🌴 🚦 🚗 🏫  🏡   _🏃 

## Highlights 👍  
- Good job acknowledging Nelson Sakwa on Behance for the [Original design idea](https://www.behance.net/sakwadesignstudio).
- SPA feature working as intended!
- Properly implemented state management using Redux!

## Required Changes ♻️
_Kindly check the inline comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

_Kindly check the inline comments marked **[OPTIONAL]** under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 16:07 UTC, rloterh commented on src/components/home.jsx
> +
- [ ] Let's improve upon the functionality of the app by adding a filter feature. Kindly ensure to a use a filter stateless component to filter data retrieved from the API, so that when the page loads, the webapp shows the list of categories that could be filtered out/searched by some parameter, for example by the name or keywords.

2023-04-19 16:07 UTC, rloterh commented on src/components/home.css
> +ul {
- [ ] Good job, cards are displaying correctly on a mobile screen. However, the styling of the list on your _Homepage_ does not conform to the alternating dual-color pattern of the provided [design template](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)). Kindly note we as much as possible want your design to match the provided [template](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)). Therefore kindly ensure that the cards of your list follow the **alternating dual-color pattern**. Each cell of the list item should have surrounding cells having **different (or slightly alternating color shade) background color(s)**.

**Your design:**        |  **The original design:**
:-------------------------:|:-------------------------:
<img width="800" alt="Home Page" src="https://user-images.githubusercontent.com/12745474/233121956-df8e95d3-574c-4f9d-a25f-cd5d6652433e.png"> | <img width="800" alt="Home Page" src="https://user-images.githubusercontent.com/12745474/142270463-4d16b9d3-7557-430c-80eb-a7c40589a4a6.png">

2023-04-19 16:07 UTC, rloterh commented on src/components/characterdetails.jsx
> +  selectedCharacter: PropTypes.objectOf(PropTypes.string.isRequired).isRequired,
- [ ] [OPTIONAL]
A runtime error is detected in the browser console. Even though this is not affecting the functionality of the app, I'll urge you to endeavor to perform some debugging regarding the same. In attempt to trace the source of the error I learnt this might be caused by mismatch in imported packages, though I've not specifically traced the source yet.

**Proptype error:**
![image](https://user-images.githubusercontent.com/12745474/233127630-3e1b5f43-f753-43f7-819c-8a33dd1dda25.png)

2023-04-19 16:07 UTC, rloterh commented on src/Redux/___test____/finalspace.test.js
> +
- [ ] Kindly ensure that test unit test includes unit test cases for the various components used in this app.

2023-04-19 16:07 UTC, rloterh commented on README.md
> +<!-- AUTHORS -->
- [ ] [OPTIONAL]
Kindly ensure that the _Getting Started_ section_ of the ReadMe is filled with the appropriate instructions on how to _setup_, _run_ and _test_ your app.

2023-04-19 16:07 UTC, rloterh commented on README.md
> +## 🚀 Loom  Video <a name="loom-Video"></a>
- [ ] Good job with project presentation, however, your missed in your presentation to highlight about a piece of the code (possibly from your code editor) that you find interesting or that you were proud of making. Let's include this missing piece in the video presentation.

2023-04-19 16:07 UTC, rloterh commented on README.md
> +## 🚀 Live Demo <a name="live-demo"></a>
- [ ] Live demo link is displaying a screen with background but no content. Let's ensure that the app is properly deployed.

**Your deployed page:**
![image](https://user-images.githubusercontent.com/12745474/233134542-fe0d2a5f-a7e4-4627-9fe4-a87783ee25a0.png)

2023-04-20 16:31 UTC, DammyShittu requested changes
Hi @ismailmunyentwari9,

## Highlights
✔️ Alternating colors in the homepage

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 16:31 UTC, DammyShittu commented on src/Redux/___test____/finalspace.test.js
> +  describe('fetchCharacters', () => {
- [ ] Kindly add more unit tests for the components in your application as suggested by the previous reviewer.

2023-04-22 09:17 UTC, mwanawabangona approved these changes
Hi @ismailmunyentwari9 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job Implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form]([https://airtable.com/shrQAqnBwek5a0O0s).](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-04-22 09:19 UTC, merged